### ISSUE TITLE
[Accessibility] Add alt attribute on website logo

### ISSUE THREAD

**Issue by OfficialMarinho** [microsoft/api-extractor.com-website#23]
The website logo [don't have a alt attribute](https://github.com/microsoft/api-extractor.com-website/blob/699dcea6edde95f64fb6d572e582f97cc9865d94/permalinks/home.html#L12). This attribute is required for a better user experience and a better social inclusion.

**Comment by octogonz** [comment]
Want to create a PR?

**Comment by OfficialMarinho** [comment]
For sure, @octogonz! Can you help me?

**Comment by isa3bel** [comment]
I can do this one!

**Comment by OfficialMarinho** [comment]
> I can do this one!

Thanks for that, Isa! I appreciate that 😄

**Comment by isa3bel** [comment]
since it completed, can we remove this issue?
