### ISSUE TITLE
docs: creating custom documenter 

### ISSUE THREAD

**Issue by johnhooks** [microsoft/api-extractor.com-website#55]
## The Issue

I tried to follow the instructions to create a custom documenter, in [custom_docs.md](https://github.com/microsoft/api-extractor.com-website/blob/e0e6a45d55509a2a5c64eae6a61e48374fe3c3da/pages/setup/custom_docs.md?plain=1#L22). 

Though on the first step `npm install`, I received this error:

```sh
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

<details>
 <summary>npm complete log</summary>
<pre>0 verbose cli /Users/johnhooks/.nvm/versions/node/v18.8.0/bin/node /Users/johnhooks/.nvm/versions/node/v18.8.0/bin/npm
1 info using npm@8.18.0
2 info using node@v18.8.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/johnhooks/Projects/rushstack/apps/api-documenter/.npmrc Completed in 1ms
10 timing config:load:project Completed in 11ms
11 timing config:load:file:/Users/johnhooks/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/johnhooks/.nvm/versions/node/v18.8.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 21ms
19 timing npm:load:configload Completed in 21ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 19ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/Users/johnhooks/.npm/_logs
28 verbose logfile /Users/johnhooks/.npm/_logs/2023-01-02T19_08_57_232Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 54ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing arborist:ctor Completed in 0ms
37 timing idealTree:init Completed in 15ms
38 timing idealTree:userRequests Completed in 0ms
39 silly idealTree buildDeps
40 timing idealTree Completed in 19ms
41 timing command:install Completed in 35ms
42 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
42 verbose stack     at unsupportedURLType (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:298:15)
42 verbose stack     at fromURL (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:358:13)
42 verbose stack     at Function.resolve (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:81:12)
42 verbose stack     at [nodeFromEdge] (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1106:22)
42 verbose stack     at [buildDepStep] (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:36)
42 verbose stack     at [buildDeps] (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:824:31)
42 verbose stack     at Arborist.buildIdealTree (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:29)
42 verbose stack     at async Promise.all (index 1)
42 verbose stack     at async Arborist.reify (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
42 verbose stack     at async Install.exec (/Users/johnhooks/.nvm/versions/node/v18.8.0/lib/node_modules/npm/lib/commands/install.js:145:5)
43 verbose cwd /Users/johnhooks/Projects/rushstack/apps/api-documenter
44 verbose Darwin 21.4.0
45 verbose node v18.8.0
46 verbose npm  v8.18.0
47 error code EUNSUPPORTEDPROTOCOL
48 error Unsupported URL Type "workspace:": workspace:*
49 verbose exit 1
50 timing npm Completed in 259ms
51 verbose unfinished npm timer reify 1672686537453
52 verbose unfinished npm timer reify:loadTrees 1672686537464
53 verbose unfinished npm timer idealTree:buildDeps 1672686537480
54 verbose unfinished npm timer idealTree:#root 1672686537481
55 verbose code 1
56 error A complete log of this run can be found in:
56 error     /Users/johnhooks/.npm/_logs/2023-01-02T19_08_57_232Z-debug-0.log</pre>
</details>

## Using

- `node` v18.8.0
- `npm` v9.2.0

**Comment by octogonz** [comment]
Good point. This no longer works after we migrated to use PNPM workspaces. We'll update the docs.

**Comment by johnhooks** [comment]
Thanks you. I figured it was something like that, but I didn't want to dig into the issue without confirming. Is the general strategy to create a custom formatter still relevant? I want to create one for the [dinero.js](https://github.com/dinerojs/dinero.js) docs. I helped move the project to using `api-extractor` for rolling up declarations, but now I want to start using the other features.

**Comment by octogonz** [comment]
Fixed in https://github.com/microsoft/rushstack-websites/pull/139
