### ISSUE TITLE
tvchak.com This site distributes azure microsoft cloud api, so please give me api sniffer

### ISSUE THREAD

**Issue by wlsstn1** [microsoft/api-extractor.com-website#56]
microsoft cloud m3u8 sniffer please. If possible, use chrome extension.

**Comment by octogonz** [comment]
Out of scope for this project.

**Comment by wlsstn1** [comment]
네이버 메일 앱에서 보냈습니다.
날짜: 2023.01.15 오후 03:22:00 (GMT+09:00)
제목: Re: [microsoft/api-extractor.com-website] tvchak.com This site distributes azure microsoft cloud api, so please give me api sniffer (Issue #56)

Closed #56 as completed.
